applications:
- name: moneygr2
  buildpacks:
  - https://github.com/cloudfoundry/java-buildpack#v4.16
  path: ./target/moneygr2-0.0.1-SNAPSHOT.jar
  env:
    JAVA_OPTS: '-XX:ReservedCodeCacheSize=32M -Xss512k -XX:+PrintCodeCache'
    JBP_CONFIG_OPEN_JDK_JRE: '[memory_calculator: {stack_threads: 24}, jre: { version: 11.+}]'
  memory: 512m